/*
Stacks 2.0+ RPC API

Testing FeesAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package rpc_client

import (
	"context"
	"testing"

	"github.com/icon-project/stacks-go-sdk/pkg/rpc_client"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func Test_rpc_client_FeesAPIService(t *testing.T) {

	configuration := rpc_client.NewConfiguration()
	apiClient := rpc_client.NewAPIClient(configuration)

	t.Run("Test FeesAPIService GetFeeTransfer", func(t *testing.T) {
		ctx := context.WithValue(context.Background(), rpc_client.ContextServerIndex, 1)
		resp, httpRes, err := apiClient.FeesAPI.GetFeeTransfer(ctx).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test FeesAPIService PostFeeTransaction", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		ctx := context.WithValue(context.Background(), rpc_client.ContextServerIndex, 1)
		resp, httpRes, err := apiClient.FeesAPI.PostFeeTransaction(ctx).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
