/*
Stacks Blockchain API

Welcome to the API reference overview for the [Stacks Blockchain API](https://docs.hiro.so/stacks-blockchain-api).        [Download Postman collection](https://hirosystems.github.io/stacks-blockchain-api/collection.json)

API version: v7.14.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package stacks_blockchain_api_client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the NetworkBlockTimesResponseMainnet type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NetworkBlockTimesResponseMainnet{}

// NetworkBlockTimesResponseMainnet struct for NetworkBlockTimesResponseMainnet
type NetworkBlockTimesResponseMainnet struct {
	TargetBlockTime int32 `json:"target_block_time"`
}

type _NetworkBlockTimesResponseMainnet NetworkBlockTimesResponseMainnet

// NewNetworkBlockTimesResponseMainnet instantiates a new NetworkBlockTimesResponseMainnet object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNetworkBlockTimesResponseMainnet(targetBlockTime int32) *NetworkBlockTimesResponseMainnet {
	this := NetworkBlockTimesResponseMainnet{}
	this.TargetBlockTime = targetBlockTime
	return &this
}

// NewNetworkBlockTimesResponseMainnetWithDefaults instantiates a new NetworkBlockTimesResponseMainnet object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNetworkBlockTimesResponseMainnetWithDefaults() *NetworkBlockTimesResponseMainnet {
	this := NetworkBlockTimesResponseMainnet{}
	return &this
}

// GetTargetBlockTime returns the TargetBlockTime field value
func (o *NetworkBlockTimesResponseMainnet) GetTargetBlockTime() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TargetBlockTime
}

// GetTargetBlockTimeOk returns a tuple with the TargetBlockTime field value
// and a boolean to check if the value has been set.
func (o *NetworkBlockTimesResponseMainnet) GetTargetBlockTimeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TargetBlockTime, true
}

// SetTargetBlockTime sets field value
func (o *NetworkBlockTimesResponseMainnet) SetTargetBlockTime(v int32) {
	o.TargetBlockTime = v
}

func (o NetworkBlockTimesResponseMainnet) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NetworkBlockTimesResponseMainnet) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["target_block_time"] = o.TargetBlockTime
	return toSerialize, nil
}

func (o *NetworkBlockTimesResponseMainnet) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"target_block_time",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varNetworkBlockTimesResponseMainnet := _NetworkBlockTimesResponseMainnet{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varNetworkBlockTimesResponseMainnet)

	if err != nil {
		return err
	}

	*o = NetworkBlockTimesResponseMainnet(varNetworkBlockTimesResponseMainnet)

	return err
}

type NullableNetworkBlockTimesResponseMainnet struct {
	value *NetworkBlockTimesResponseMainnet
	isSet bool
}

func (v NullableNetworkBlockTimesResponseMainnet) Get() *NetworkBlockTimesResponseMainnet {
	return v.value
}

func (v *NullableNetworkBlockTimesResponseMainnet) Set(val *NetworkBlockTimesResponseMainnet) {
	v.value = val
	v.isSet = true
}

func (v NullableNetworkBlockTimesResponseMainnet) IsSet() bool {
	return v.isSet
}

func (v *NullableNetworkBlockTimesResponseMainnet) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNetworkBlockTimesResponseMainnet(val *NetworkBlockTimesResponseMainnet) *NullableNetworkBlockTimesResponseMainnet {
	return &NullableNetworkBlockTimesResponseMainnet{value: val, isSet: true}
}

func (v NullableNetworkBlockTimesResponseMainnet) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNetworkBlockTimesResponseMainnet) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


