/*
Stacks Blockchain API

Welcome to the API reference overview for the [Stacks Blockchain API](https://docs.hiro.so/stacks-blockchain-api).        [Download Postman collection](https://hirosystems.github.io/stacks-blockchain-api/collection.json)

API version: v8.1.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package stacks_blockchain_api_client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TokenTransferTransaction1PostConditionsInnerAnyOfPrincipalAnyOf1 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TokenTransferTransaction1PostConditionsInnerAnyOfPrincipalAnyOf1{}

// TokenTransferTransaction1PostConditionsInnerAnyOfPrincipalAnyOf1 struct for TokenTransferTransaction1PostConditionsInnerAnyOfPrincipalAnyOf1
type TokenTransferTransaction1PostConditionsInnerAnyOfPrincipalAnyOf1 struct {
	TypeId string `json:"type_id"`
	Address string `json:"address"`
}

type _TokenTransferTransaction1PostConditionsInnerAnyOfPrincipalAnyOf1 TokenTransferTransaction1PostConditionsInnerAnyOfPrincipalAnyOf1

// NewTokenTransferTransaction1PostConditionsInnerAnyOfPrincipalAnyOf1 instantiates a new TokenTransferTransaction1PostConditionsInnerAnyOfPrincipalAnyOf1 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTokenTransferTransaction1PostConditionsInnerAnyOfPrincipalAnyOf1(typeId string, address string) *TokenTransferTransaction1PostConditionsInnerAnyOfPrincipalAnyOf1 {
	this := TokenTransferTransaction1PostConditionsInnerAnyOfPrincipalAnyOf1{}
	this.TypeId = typeId
	this.Address = address
	return &this
}

// NewTokenTransferTransaction1PostConditionsInnerAnyOfPrincipalAnyOf1WithDefaults instantiates a new TokenTransferTransaction1PostConditionsInnerAnyOfPrincipalAnyOf1 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTokenTransferTransaction1PostConditionsInnerAnyOfPrincipalAnyOf1WithDefaults() *TokenTransferTransaction1PostConditionsInnerAnyOfPrincipalAnyOf1 {
	this := TokenTransferTransaction1PostConditionsInnerAnyOfPrincipalAnyOf1{}
	return &this
}

// GetTypeId returns the TypeId field value
func (o *TokenTransferTransaction1PostConditionsInnerAnyOfPrincipalAnyOf1) GetTypeId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TypeId
}

// GetTypeIdOk returns a tuple with the TypeId field value
// and a boolean to check if the value has been set.
func (o *TokenTransferTransaction1PostConditionsInnerAnyOfPrincipalAnyOf1) GetTypeIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TypeId, true
}

// SetTypeId sets field value
func (o *TokenTransferTransaction1PostConditionsInnerAnyOfPrincipalAnyOf1) SetTypeId(v string) {
	o.TypeId = v
}

// GetAddress returns the Address field value
func (o *TokenTransferTransaction1PostConditionsInnerAnyOfPrincipalAnyOf1) GetAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Address
}

// GetAddressOk returns a tuple with the Address field value
// and a boolean to check if the value has been set.
func (o *TokenTransferTransaction1PostConditionsInnerAnyOfPrincipalAnyOf1) GetAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Address, true
}

// SetAddress sets field value
func (o *TokenTransferTransaction1PostConditionsInnerAnyOfPrincipalAnyOf1) SetAddress(v string) {
	o.Address = v
}

func (o TokenTransferTransaction1PostConditionsInnerAnyOfPrincipalAnyOf1) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TokenTransferTransaction1PostConditionsInnerAnyOfPrincipalAnyOf1) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type_id"] = o.TypeId
	toSerialize["address"] = o.Address
	return toSerialize, nil
}

func (o *TokenTransferTransaction1PostConditionsInnerAnyOfPrincipalAnyOf1) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type_id",
		"address",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTokenTransferTransaction1PostConditionsInnerAnyOfPrincipalAnyOf1 := _TokenTransferTransaction1PostConditionsInnerAnyOfPrincipalAnyOf1{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTokenTransferTransaction1PostConditionsInnerAnyOfPrincipalAnyOf1)

	if err != nil {
		return err
	}

	*o = TokenTransferTransaction1PostConditionsInnerAnyOfPrincipalAnyOf1(varTokenTransferTransaction1PostConditionsInnerAnyOfPrincipalAnyOf1)

	return err
}

type NullableTokenTransferTransaction1PostConditionsInnerAnyOfPrincipalAnyOf1 struct {
	value *TokenTransferTransaction1PostConditionsInnerAnyOfPrincipalAnyOf1
	isSet bool
}

func (v NullableTokenTransferTransaction1PostConditionsInnerAnyOfPrincipalAnyOf1) Get() *TokenTransferTransaction1PostConditionsInnerAnyOfPrincipalAnyOf1 {
	return v.value
}

func (v *NullableTokenTransferTransaction1PostConditionsInnerAnyOfPrincipalAnyOf1) Set(val *TokenTransferTransaction1PostConditionsInnerAnyOfPrincipalAnyOf1) {
	v.value = val
	v.isSet = true
}

func (v NullableTokenTransferTransaction1PostConditionsInnerAnyOfPrincipalAnyOf1) IsSet() bool {
	return v.isSet
}

func (v *NullableTokenTransferTransaction1PostConditionsInnerAnyOfPrincipalAnyOf1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTokenTransferTransaction1PostConditionsInnerAnyOfPrincipalAnyOf1(val *TokenTransferTransaction1PostConditionsInnerAnyOfPrincipalAnyOf1) *NullableTokenTransferTransaction1PostConditionsInnerAnyOfPrincipalAnyOf1 {
	return &NullableTokenTransferTransaction1PostConditionsInnerAnyOfPrincipalAnyOf1{value: val, isSet: true}
}

func (v NullableTokenTransferTransaction1PostConditionsInnerAnyOfPrincipalAnyOf1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTokenTransferTransaction1PostConditionsInnerAnyOfPrincipalAnyOf1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


