/*
Stacks Blockchain API

Welcome to the API reference overview for the [Stacks Blockchain API](https://docs.hiro.so/stacks-blockchain-api).        [Download Postman collection](https://hirosystems.github.io/stacks-blockchain-api/collection.json)

API version: v7.14.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package stacks_blockchain_api_client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GetBtcBalance200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetBtcBalance200Response{}

// GetBtcBalance200Response struct for GetBtcBalance200Response
type GetBtcBalance200Response struct {
	// Address balance in BTC
	Balance float32 `json:"balance"`
}

type _GetBtcBalance200Response GetBtcBalance200Response

// NewGetBtcBalance200Response instantiates a new GetBtcBalance200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetBtcBalance200Response(balance float32) *GetBtcBalance200Response {
	this := GetBtcBalance200Response{}
	this.Balance = balance
	return &this
}

// NewGetBtcBalance200ResponseWithDefaults instantiates a new GetBtcBalance200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetBtcBalance200ResponseWithDefaults() *GetBtcBalance200Response {
	this := GetBtcBalance200Response{}
	return &this
}

// GetBalance returns the Balance field value
func (o *GetBtcBalance200Response) GetBalance() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Balance
}

// GetBalanceOk returns a tuple with the Balance field value
// and a boolean to check if the value has been set.
func (o *GetBtcBalance200Response) GetBalanceOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Balance, true
}

// SetBalance sets field value
func (o *GetBtcBalance200Response) SetBalance(v float32) {
	o.Balance = v
}

func (o GetBtcBalance200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetBtcBalance200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["balance"] = o.Balance
	return toSerialize, nil
}

func (o *GetBtcBalance200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"balance",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetBtcBalance200Response := _GetBtcBalance200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetBtcBalance200Response)

	if err != nil {
		return err
	}

	*o = GetBtcBalance200Response(varGetBtcBalance200Response)

	return err
}

type NullableGetBtcBalance200Response struct {
	value *GetBtcBalance200Response
	isSet bool
}

func (v NullableGetBtcBalance200Response) Get() *GetBtcBalance200Response {
	return v.value
}

func (v *NullableGetBtcBalance200Response) Set(val *GetBtcBalance200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetBtcBalance200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetBtcBalance200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetBtcBalance200Response(val *GetBtcBalance200Response) *NullableGetBtcBalance200Response {
	return &NullableGetBtcBalance200Response{value: val, isSet: true}
}

func (v NullableGetBtcBalance200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetBtcBalance200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


