/*
Stacks Blockchain API

Welcome to the API reference overview for the [Stacks Blockchain API](https://docs.hiro.so/stacks-blockchain-api).        [Download Postman collection](https://hirosystems.github.io/stacks-blockchain-api/collection.json)

API version: v7.14.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package stacks_blockchain_api_client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SearchById404Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SearchById404Response{}

// SearchById404Response struct for SearchById404Response
type SearchById404Response struct {
	Found bool `json:"found"`
	Result SearchById404ResponseResult `json:"result"`
	Error string `json:"error"`
}

type _SearchById404Response SearchById404Response

// NewSearchById404Response instantiates a new SearchById404Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSearchById404Response(found bool, result SearchById404ResponseResult, error_ string) *SearchById404Response {
	this := SearchById404Response{}
	this.Found = found
	this.Result = result
	this.Error = error_
	return &this
}

// NewSearchById404ResponseWithDefaults instantiates a new SearchById404Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSearchById404ResponseWithDefaults() *SearchById404Response {
	this := SearchById404Response{}
	return &this
}

// GetFound returns the Found field value
func (o *SearchById404Response) GetFound() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Found
}

// GetFoundOk returns a tuple with the Found field value
// and a boolean to check if the value has been set.
func (o *SearchById404Response) GetFoundOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Found, true
}

// SetFound sets field value
func (o *SearchById404Response) SetFound(v bool) {
	o.Found = v
}

// GetResult returns the Result field value
func (o *SearchById404Response) GetResult() SearchById404ResponseResult {
	if o == nil {
		var ret SearchById404ResponseResult
		return ret
	}

	return o.Result
}

// GetResultOk returns a tuple with the Result field value
// and a boolean to check if the value has been set.
func (o *SearchById404Response) GetResultOk() (*SearchById404ResponseResult, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Result, true
}

// SetResult sets field value
func (o *SearchById404Response) SetResult(v SearchById404ResponseResult) {
	o.Result = v
}

// GetError returns the Error field value
func (o *SearchById404Response) GetError() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Error
}

// GetErrorOk returns a tuple with the Error field value
// and a boolean to check if the value has been set.
func (o *SearchById404Response) GetErrorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Error, true
}

// SetError sets field value
func (o *SearchById404Response) SetError(v string) {
	o.Error = v
}

func (o SearchById404Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SearchById404Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["found"] = o.Found
	toSerialize["result"] = o.Result
	toSerialize["error"] = o.Error
	return toSerialize, nil
}

func (o *SearchById404Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"found",
		"result",
		"error",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSearchById404Response := _SearchById404Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSearchById404Response)

	if err != nil {
		return err
	}

	*o = SearchById404Response(varSearchById404Response)

	return err
}

type NullableSearchById404Response struct {
	value *SearchById404Response
	isSet bool
}

func (v NullableSearchById404Response) Get() *SearchById404Response {
	return v.value
}

func (v *NullableSearchById404Response) Set(val *SearchById404Response) {
	v.value = val
	v.isSet = true
}

func (v NullableSearchById404Response) IsSet() bool {
	return v.isSet
}

func (v *NullableSearchById404Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSearchById404Response(val *SearchById404Response) *NullableSearchById404Response {
	return &NullableSearchById404Response{value: val, isSet: true}
}

func (v NullableSearchById404Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSearchById404Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


