/*
Stacks Blockchain API

Welcome to the API reference overview for the [Stacks Blockchain API](https://docs.hiro.so/stacks-blockchain-api).        [Download Postman collection](https://hirosystems.github.io/stacks-blockchain-api/collection.json)

API version: v7.14.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package stacks_blockchain_api_client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the FungibleTokenAssetTransactionEvent1AllOfAsset type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FungibleTokenAssetTransactionEvent1AllOfAsset{}

// FungibleTokenAssetTransactionEvent1AllOfAsset struct for FungibleTokenAssetTransactionEvent1AllOfAsset
type FungibleTokenAssetTransactionEvent1AllOfAsset struct {
	AssetEventType StxAssetTransactionEvent1AllOfAssetAssetEventType `json:"asset_event_type"`
	AssetId string `json:"asset_id"`
	Sender string `json:"sender"`
	Recipient string `json:"recipient"`
	Amount string `json:"amount"`
}

type _FungibleTokenAssetTransactionEvent1AllOfAsset FungibleTokenAssetTransactionEvent1AllOfAsset

// NewFungibleTokenAssetTransactionEvent1AllOfAsset instantiates a new FungibleTokenAssetTransactionEvent1AllOfAsset object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFungibleTokenAssetTransactionEvent1AllOfAsset(assetEventType StxAssetTransactionEvent1AllOfAssetAssetEventType, assetId string, sender string, recipient string, amount string) *FungibleTokenAssetTransactionEvent1AllOfAsset {
	this := FungibleTokenAssetTransactionEvent1AllOfAsset{}
	this.AssetEventType = assetEventType
	this.AssetId = assetId
	this.Sender = sender
	this.Recipient = recipient
	this.Amount = amount
	return &this
}

// NewFungibleTokenAssetTransactionEvent1AllOfAssetWithDefaults instantiates a new FungibleTokenAssetTransactionEvent1AllOfAsset object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFungibleTokenAssetTransactionEvent1AllOfAssetWithDefaults() *FungibleTokenAssetTransactionEvent1AllOfAsset {
	this := FungibleTokenAssetTransactionEvent1AllOfAsset{}
	return &this
}

// GetAssetEventType returns the AssetEventType field value
func (o *FungibleTokenAssetTransactionEvent1AllOfAsset) GetAssetEventType() StxAssetTransactionEvent1AllOfAssetAssetEventType {
	if o == nil {
		var ret StxAssetTransactionEvent1AllOfAssetAssetEventType
		return ret
	}

	return o.AssetEventType
}

// GetAssetEventTypeOk returns a tuple with the AssetEventType field value
// and a boolean to check if the value has been set.
func (o *FungibleTokenAssetTransactionEvent1AllOfAsset) GetAssetEventTypeOk() (*StxAssetTransactionEvent1AllOfAssetAssetEventType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AssetEventType, true
}

// SetAssetEventType sets field value
func (o *FungibleTokenAssetTransactionEvent1AllOfAsset) SetAssetEventType(v StxAssetTransactionEvent1AllOfAssetAssetEventType) {
	o.AssetEventType = v
}

// GetAssetId returns the AssetId field value
func (o *FungibleTokenAssetTransactionEvent1AllOfAsset) GetAssetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AssetId
}

// GetAssetIdOk returns a tuple with the AssetId field value
// and a boolean to check if the value has been set.
func (o *FungibleTokenAssetTransactionEvent1AllOfAsset) GetAssetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AssetId, true
}

// SetAssetId sets field value
func (o *FungibleTokenAssetTransactionEvent1AllOfAsset) SetAssetId(v string) {
	o.AssetId = v
}

// GetSender returns the Sender field value
func (o *FungibleTokenAssetTransactionEvent1AllOfAsset) GetSender() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Sender
}

// GetSenderOk returns a tuple with the Sender field value
// and a boolean to check if the value has been set.
func (o *FungibleTokenAssetTransactionEvent1AllOfAsset) GetSenderOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Sender, true
}

// SetSender sets field value
func (o *FungibleTokenAssetTransactionEvent1AllOfAsset) SetSender(v string) {
	o.Sender = v
}

// GetRecipient returns the Recipient field value
func (o *FungibleTokenAssetTransactionEvent1AllOfAsset) GetRecipient() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Recipient
}

// GetRecipientOk returns a tuple with the Recipient field value
// and a boolean to check if the value has been set.
func (o *FungibleTokenAssetTransactionEvent1AllOfAsset) GetRecipientOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Recipient, true
}

// SetRecipient sets field value
func (o *FungibleTokenAssetTransactionEvent1AllOfAsset) SetRecipient(v string) {
	o.Recipient = v
}

// GetAmount returns the Amount field value
func (o *FungibleTokenAssetTransactionEvent1AllOfAsset) GetAmount() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Amount
}

// GetAmountOk returns a tuple with the Amount field value
// and a boolean to check if the value has been set.
func (o *FungibleTokenAssetTransactionEvent1AllOfAsset) GetAmountOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Amount, true
}

// SetAmount sets field value
func (o *FungibleTokenAssetTransactionEvent1AllOfAsset) SetAmount(v string) {
	o.Amount = v
}

func (o FungibleTokenAssetTransactionEvent1AllOfAsset) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FungibleTokenAssetTransactionEvent1AllOfAsset) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["asset_event_type"] = o.AssetEventType
	toSerialize["asset_id"] = o.AssetId
	toSerialize["sender"] = o.Sender
	toSerialize["recipient"] = o.Recipient
	toSerialize["amount"] = o.Amount
	return toSerialize, nil
}

func (o *FungibleTokenAssetTransactionEvent1AllOfAsset) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"asset_event_type",
		"asset_id",
		"sender",
		"recipient",
		"amount",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varFungibleTokenAssetTransactionEvent1AllOfAsset := _FungibleTokenAssetTransactionEvent1AllOfAsset{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varFungibleTokenAssetTransactionEvent1AllOfAsset)

	if err != nil {
		return err
	}

	*o = FungibleTokenAssetTransactionEvent1AllOfAsset(varFungibleTokenAssetTransactionEvent1AllOfAsset)

	return err
}

type NullableFungibleTokenAssetTransactionEvent1AllOfAsset struct {
	value *FungibleTokenAssetTransactionEvent1AllOfAsset
	isSet bool
}

func (v NullableFungibleTokenAssetTransactionEvent1AllOfAsset) Get() *FungibleTokenAssetTransactionEvent1AllOfAsset {
	return v.value
}

func (v *NullableFungibleTokenAssetTransactionEvent1AllOfAsset) Set(val *FungibleTokenAssetTransactionEvent1AllOfAsset) {
	v.value = val
	v.isSet = true
}

func (v NullableFungibleTokenAssetTransactionEvent1AllOfAsset) IsSet() bool {
	return v.isSet
}

func (v *NullableFungibleTokenAssetTransactionEvent1AllOfAsset) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFungibleTokenAssetTransactionEvent1AllOfAsset(val *FungibleTokenAssetTransactionEvent1AllOfAsset) *NullableFungibleTokenAssetTransactionEvent1AllOfAsset {
	return &NullableFungibleTokenAssetTransactionEvent1AllOfAsset{value: val, isSet: true}
}

func (v NullableFungibleTokenAssetTransactionEvent1AllOfAsset) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFungibleTokenAssetTransactionEvent1AllOfAsset) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


