/*
Stacks Blockchain API

Welcome to the API reference overview for the [Stacks Blockchain API](https://docs.hiro.so/stacks-blockchain-api).        [Download Postman collection](https://hirosystems.github.io/stacks-blockchain-api/collection.json)

API version: v8.1.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package stacks_blockchain_api_client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the NonFungibleTokenAssetTransactionEvent1 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NonFungibleTokenAssetTransactionEvent1{}

// NonFungibleTokenAssetTransactionEvent1 struct for NonFungibleTokenAssetTransactionEvent1
type NonFungibleTokenAssetTransactionEvent1 struct {
	EventIndex int32 `json:"event_index"`
	EventType string `json:"event_type"`
	TxId string `json:"tx_id"`
	Asset NonFungibleTokenAssetTransactionEvent1AllOfAsset `json:"asset"`
}

type _NonFungibleTokenAssetTransactionEvent1 NonFungibleTokenAssetTransactionEvent1

// NewNonFungibleTokenAssetTransactionEvent1 instantiates a new NonFungibleTokenAssetTransactionEvent1 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNonFungibleTokenAssetTransactionEvent1(eventIndex int32, eventType string, txId string, asset NonFungibleTokenAssetTransactionEvent1AllOfAsset) *NonFungibleTokenAssetTransactionEvent1 {
	this := NonFungibleTokenAssetTransactionEvent1{}
	this.EventIndex = eventIndex
	this.EventType = eventType
	this.TxId = txId
	this.Asset = asset
	return &this
}

// NewNonFungibleTokenAssetTransactionEvent1WithDefaults instantiates a new NonFungibleTokenAssetTransactionEvent1 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNonFungibleTokenAssetTransactionEvent1WithDefaults() *NonFungibleTokenAssetTransactionEvent1 {
	this := NonFungibleTokenAssetTransactionEvent1{}
	return &this
}

// GetEventIndex returns the EventIndex field value
func (o *NonFungibleTokenAssetTransactionEvent1) GetEventIndex() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.EventIndex
}

// GetEventIndexOk returns a tuple with the EventIndex field value
// and a boolean to check if the value has been set.
func (o *NonFungibleTokenAssetTransactionEvent1) GetEventIndexOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EventIndex, true
}

// SetEventIndex sets field value
func (o *NonFungibleTokenAssetTransactionEvent1) SetEventIndex(v int32) {
	o.EventIndex = v
}

// GetEventType returns the EventType field value
func (o *NonFungibleTokenAssetTransactionEvent1) GetEventType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EventType
}

// GetEventTypeOk returns a tuple with the EventType field value
// and a boolean to check if the value has been set.
func (o *NonFungibleTokenAssetTransactionEvent1) GetEventTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EventType, true
}

// SetEventType sets field value
func (o *NonFungibleTokenAssetTransactionEvent1) SetEventType(v string) {
	o.EventType = v
}

// GetTxId returns the TxId field value
func (o *NonFungibleTokenAssetTransactionEvent1) GetTxId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TxId
}

// GetTxIdOk returns a tuple with the TxId field value
// and a boolean to check if the value has been set.
func (o *NonFungibleTokenAssetTransactionEvent1) GetTxIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TxId, true
}

// SetTxId sets field value
func (o *NonFungibleTokenAssetTransactionEvent1) SetTxId(v string) {
	o.TxId = v
}

// GetAsset returns the Asset field value
func (o *NonFungibleTokenAssetTransactionEvent1) GetAsset() NonFungibleTokenAssetTransactionEvent1AllOfAsset {
	if o == nil {
		var ret NonFungibleTokenAssetTransactionEvent1AllOfAsset
		return ret
	}

	return o.Asset
}

// GetAssetOk returns a tuple with the Asset field value
// and a boolean to check if the value has been set.
func (o *NonFungibleTokenAssetTransactionEvent1) GetAssetOk() (*NonFungibleTokenAssetTransactionEvent1AllOfAsset, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Asset, true
}

// SetAsset sets field value
func (o *NonFungibleTokenAssetTransactionEvent1) SetAsset(v NonFungibleTokenAssetTransactionEvent1AllOfAsset) {
	o.Asset = v
}

func (o NonFungibleTokenAssetTransactionEvent1) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NonFungibleTokenAssetTransactionEvent1) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["event_index"] = o.EventIndex
	toSerialize["event_type"] = o.EventType
	toSerialize["tx_id"] = o.TxId
	toSerialize["asset"] = o.Asset
	return toSerialize, nil
}

func (o *NonFungibleTokenAssetTransactionEvent1) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"event_index",
		"event_type",
		"tx_id",
		"asset",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varNonFungibleTokenAssetTransactionEvent1 := _NonFungibleTokenAssetTransactionEvent1{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varNonFungibleTokenAssetTransactionEvent1)

	if err != nil {
		return err
	}

	*o = NonFungibleTokenAssetTransactionEvent1(varNonFungibleTokenAssetTransactionEvent1)

	return err
}

type NullableNonFungibleTokenAssetTransactionEvent1 struct {
	value *NonFungibleTokenAssetTransactionEvent1
	isSet bool
}

func (v NullableNonFungibleTokenAssetTransactionEvent1) Get() *NonFungibleTokenAssetTransactionEvent1 {
	return v.value
}

func (v *NullableNonFungibleTokenAssetTransactionEvent1) Set(val *NonFungibleTokenAssetTransactionEvent1) {
	v.value = val
	v.isSet = true
}

func (v NullableNonFungibleTokenAssetTransactionEvent1) IsSet() bool {
	return v.isSet
}

func (v *NullableNonFungibleTokenAssetTransactionEvent1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNonFungibleTokenAssetTransactionEvent1(val *NonFungibleTokenAssetTransactionEvent1) *NullableNonFungibleTokenAssetTransactionEvent1 {
	return &NullableNonFungibleTokenAssetTransactionEvent1{value: val, isSet: true}
}

func (v NullableNonFungibleTokenAssetTransactionEvent1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNonFungibleTokenAssetTransactionEvent1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


