/*
Stacks Blockchain API

Welcome to the API reference overview for the [Stacks Blockchain API](https://docs.hiro.so/stacks-blockchain-api).        [Download Postman collection](https://hirosystems.github.io/stacks-blockchain-api/collection.json)

API version: v7.14.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package stacks_blockchain_api_client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TokenTransferTransactionPostConditionsInnerAnyOf2 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TokenTransferTransactionPostConditionsInnerAnyOf2{}

// TokenTransferTransactionPostConditionsInnerAnyOf2 struct for TokenTransferTransactionPostConditionsInnerAnyOf2
type TokenTransferTransactionPostConditionsInnerAnyOf2 struct {
	Principal TokenTransferTransactionPostConditionsInnerAnyOfPrincipal `json:"principal"`
	ConditionCode TokenTransferTransactionPostConditionsInnerAnyOf2ConditionCode `json:"condition_code"`
	Type string `json:"type"`
	AssetValue TokenTransferTransactionPostConditionsInnerAnyOf2AssetValue `json:"asset_value"`
	Asset TokenTransferTransactionPostConditionsInnerAnyOf1Asset `json:"asset"`
}

type _TokenTransferTransactionPostConditionsInnerAnyOf2 TokenTransferTransactionPostConditionsInnerAnyOf2

// NewTokenTransferTransactionPostConditionsInnerAnyOf2 instantiates a new TokenTransferTransactionPostConditionsInnerAnyOf2 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTokenTransferTransactionPostConditionsInnerAnyOf2(principal TokenTransferTransactionPostConditionsInnerAnyOfPrincipal, conditionCode TokenTransferTransactionPostConditionsInnerAnyOf2ConditionCode, type_ string, assetValue TokenTransferTransactionPostConditionsInnerAnyOf2AssetValue, asset TokenTransferTransactionPostConditionsInnerAnyOf1Asset) *TokenTransferTransactionPostConditionsInnerAnyOf2 {
	this := TokenTransferTransactionPostConditionsInnerAnyOf2{}
	this.Principal = principal
	this.ConditionCode = conditionCode
	this.Type = type_
	this.AssetValue = assetValue
	this.Asset = asset
	return &this
}

// NewTokenTransferTransactionPostConditionsInnerAnyOf2WithDefaults instantiates a new TokenTransferTransactionPostConditionsInnerAnyOf2 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTokenTransferTransactionPostConditionsInnerAnyOf2WithDefaults() *TokenTransferTransactionPostConditionsInnerAnyOf2 {
	this := TokenTransferTransactionPostConditionsInnerAnyOf2{}
	return &this
}

// GetPrincipal returns the Principal field value
func (o *TokenTransferTransactionPostConditionsInnerAnyOf2) GetPrincipal() TokenTransferTransactionPostConditionsInnerAnyOfPrincipal {
	if o == nil {
		var ret TokenTransferTransactionPostConditionsInnerAnyOfPrincipal
		return ret
	}

	return o.Principal
}

// GetPrincipalOk returns a tuple with the Principal field value
// and a boolean to check if the value has been set.
func (o *TokenTransferTransactionPostConditionsInnerAnyOf2) GetPrincipalOk() (*TokenTransferTransactionPostConditionsInnerAnyOfPrincipal, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Principal, true
}

// SetPrincipal sets field value
func (o *TokenTransferTransactionPostConditionsInnerAnyOf2) SetPrincipal(v TokenTransferTransactionPostConditionsInnerAnyOfPrincipal) {
	o.Principal = v
}

// GetConditionCode returns the ConditionCode field value
func (o *TokenTransferTransactionPostConditionsInnerAnyOf2) GetConditionCode() TokenTransferTransactionPostConditionsInnerAnyOf2ConditionCode {
	if o == nil {
		var ret TokenTransferTransactionPostConditionsInnerAnyOf2ConditionCode
		return ret
	}

	return o.ConditionCode
}

// GetConditionCodeOk returns a tuple with the ConditionCode field value
// and a boolean to check if the value has been set.
func (o *TokenTransferTransactionPostConditionsInnerAnyOf2) GetConditionCodeOk() (*TokenTransferTransactionPostConditionsInnerAnyOf2ConditionCode, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ConditionCode, true
}

// SetConditionCode sets field value
func (o *TokenTransferTransactionPostConditionsInnerAnyOf2) SetConditionCode(v TokenTransferTransactionPostConditionsInnerAnyOf2ConditionCode) {
	o.ConditionCode = v
}

// GetType returns the Type field value
func (o *TokenTransferTransactionPostConditionsInnerAnyOf2) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *TokenTransferTransactionPostConditionsInnerAnyOf2) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *TokenTransferTransactionPostConditionsInnerAnyOf2) SetType(v string) {
	o.Type = v
}

// GetAssetValue returns the AssetValue field value
func (o *TokenTransferTransactionPostConditionsInnerAnyOf2) GetAssetValue() TokenTransferTransactionPostConditionsInnerAnyOf2AssetValue {
	if o == nil {
		var ret TokenTransferTransactionPostConditionsInnerAnyOf2AssetValue
		return ret
	}

	return o.AssetValue
}

// GetAssetValueOk returns a tuple with the AssetValue field value
// and a boolean to check if the value has been set.
func (o *TokenTransferTransactionPostConditionsInnerAnyOf2) GetAssetValueOk() (*TokenTransferTransactionPostConditionsInnerAnyOf2AssetValue, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AssetValue, true
}

// SetAssetValue sets field value
func (o *TokenTransferTransactionPostConditionsInnerAnyOf2) SetAssetValue(v TokenTransferTransactionPostConditionsInnerAnyOf2AssetValue) {
	o.AssetValue = v
}

// GetAsset returns the Asset field value
func (o *TokenTransferTransactionPostConditionsInnerAnyOf2) GetAsset() TokenTransferTransactionPostConditionsInnerAnyOf1Asset {
	if o == nil {
		var ret TokenTransferTransactionPostConditionsInnerAnyOf1Asset
		return ret
	}

	return o.Asset
}

// GetAssetOk returns a tuple with the Asset field value
// and a boolean to check if the value has been set.
func (o *TokenTransferTransactionPostConditionsInnerAnyOf2) GetAssetOk() (*TokenTransferTransactionPostConditionsInnerAnyOf1Asset, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Asset, true
}

// SetAsset sets field value
func (o *TokenTransferTransactionPostConditionsInnerAnyOf2) SetAsset(v TokenTransferTransactionPostConditionsInnerAnyOf1Asset) {
	o.Asset = v
}

func (o TokenTransferTransactionPostConditionsInnerAnyOf2) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TokenTransferTransactionPostConditionsInnerAnyOf2) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["principal"] = o.Principal
	toSerialize["condition_code"] = o.ConditionCode
	toSerialize["type"] = o.Type
	toSerialize["asset_value"] = o.AssetValue
	toSerialize["asset"] = o.Asset
	return toSerialize, nil
}

func (o *TokenTransferTransactionPostConditionsInnerAnyOf2) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"principal",
		"condition_code",
		"type",
		"asset_value",
		"asset",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTokenTransferTransactionPostConditionsInnerAnyOf2 := _TokenTransferTransactionPostConditionsInnerAnyOf2{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTokenTransferTransactionPostConditionsInnerAnyOf2)

	if err != nil {
		return err
	}

	*o = TokenTransferTransactionPostConditionsInnerAnyOf2(varTokenTransferTransactionPostConditionsInnerAnyOf2)

	return err
}

type NullableTokenTransferTransactionPostConditionsInnerAnyOf2 struct {
	value *TokenTransferTransactionPostConditionsInnerAnyOf2
	isSet bool
}

func (v NullableTokenTransferTransactionPostConditionsInnerAnyOf2) Get() *TokenTransferTransactionPostConditionsInnerAnyOf2 {
	return v.value
}

func (v *NullableTokenTransferTransactionPostConditionsInnerAnyOf2) Set(val *TokenTransferTransactionPostConditionsInnerAnyOf2) {
	v.value = val
	v.isSet = true
}

func (v NullableTokenTransferTransactionPostConditionsInnerAnyOf2) IsSet() bool {
	return v.isSet
}

func (v *NullableTokenTransferTransactionPostConditionsInnerAnyOf2) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTokenTransferTransactionPostConditionsInnerAnyOf2(val *TokenTransferTransactionPostConditionsInnerAnyOf2) *NullableTokenTransferTransactionPostConditionsInnerAnyOf2 {
	return &NullableTokenTransferTransactionPostConditionsInnerAnyOf2{value: val, isSet: true}
}

func (v NullableTokenTransferTransactionPostConditionsInnerAnyOf2) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTokenTransferTransactionPostConditionsInnerAnyOf2) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


