/*
Stacks Blockchain API

Welcome to the API reference overview for the [Stacks Blockchain API](https://docs.hiro.so/stacks-blockchain-api).        [Download Postman collection](https://hirosystems.github.io/stacks-blockchain-api/collection.json)

API version: v7.14.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package stacks_blockchain_api_client

import (
	"encoding/json"
	"fmt"
)


// TokenTransferTransactionPostConditionsInnerAnyOf2ConditionCode struct for TokenTransferTransactionPostConditionsInnerAnyOf2ConditionCode
type TokenTransferTransactionPostConditionsInnerAnyOf2ConditionCode struct {
	String *string
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *TokenTransferTransactionPostConditionsInnerAnyOf2ConditionCode) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into String
	err = json.Unmarshal(data, &dst.String);
	if err == nil {
		jsonString, _ := json.Marshal(dst.String)
		if string(jsonString) == "{}" { // empty struct
			dst.String = nil
		} else {
			return nil // data stored in dst.String, return on the first match
		}
	} else {
		dst.String = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(TokenTransferTransactionPostConditionsInnerAnyOf2ConditionCode)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src *TokenTransferTransactionPostConditionsInnerAnyOf2ConditionCode) MarshalJSON() ([]byte, error) {
	if src.String != nil {
		return json.Marshal(&src.String)
	}

	return nil, nil // no data in anyOf schemas
}


type NullableTokenTransferTransactionPostConditionsInnerAnyOf2ConditionCode struct {
	value *TokenTransferTransactionPostConditionsInnerAnyOf2ConditionCode
	isSet bool
}

func (v NullableTokenTransferTransactionPostConditionsInnerAnyOf2ConditionCode) Get() *TokenTransferTransactionPostConditionsInnerAnyOf2ConditionCode {
	return v.value
}

func (v *NullableTokenTransferTransactionPostConditionsInnerAnyOf2ConditionCode) Set(val *TokenTransferTransactionPostConditionsInnerAnyOf2ConditionCode) {
	v.value = val
	v.isSet = true
}

func (v NullableTokenTransferTransactionPostConditionsInnerAnyOf2ConditionCode) IsSet() bool {
	return v.isSet
}

func (v *NullableTokenTransferTransactionPostConditionsInnerAnyOf2ConditionCode) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTokenTransferTransactionPostConditionsInnerAnyOf2ConditionCode(val *TokenTransferTransactionPostConditionsInnerAnyOf2ConditionCode) *NullableTokenTransferTransactionPostConditionsInnerAnyOf2ConditionCode {
	return &NullableTokenTransferTransactionPostConditionsInnerAnyOf2ConditionCode{value: val, isSet: true}
}

func (v NullableTokenTransferTransactionPostConditionsInnerAnyOf2ConditionCode) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTokenTransferTransactionPostConditionsInnerAnyOf2ConditionCode) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


