/*
Stacks Blockchain API

Welcome to the API reference overview for the [Stacks Blockchain API](https://docs.hiro.so/stacks-blockchain-api).        [Download Postman collection](https://hirosystems.github.io/stacks-blockchain-api/collection.json)

API version: v8.1.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package stacks_blockchain_api_client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the NonFungibleTokenAssetTransactionEvent1AllOfAsset type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NonFungibleTokenAssetTransactionEvent1AllOfAsset{}

// NonFungibleTokenAssetTransactionEvent1AllOfAsset struct for NonFungibleTokenAssetTransactionEvent1AllOfAsset
type NonFungibleTokenAssetTransactionEvent1AllOfAsset struct {
	AssetEventType StxAssetTransactionEvent1AllOfAssetAssetEventType `json:"asset_event_type"`
	AssetId string `json:"asset_id"`
	Sender string `json:"sender"`
	Recipient string `json:"recipient"`
	Value TokenTransferTransactionPostConditionsInnerAnyOf2AssetValue `json:"value"`
}

type _NonFungibleTokenAssetTransactionEvent1AllOfAsset NonFungibleTokenAssetTransactionEvent1AllOfAsset

// NewNonFungibleTokenAssetTransactionEvent1AllOfAsset instantiates a new NonFungibleTokenAssetTransactionEvent1AllOfAsset object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNonFungibleTokenAssetTransactionEvent1AllOfAsset(assetEventType StxAssetTransactionEvent1AllOfAssetAssetEventType, assetId string, sender string, recipient string, value TokenTransferTransactionPostConditionsInnerAnyOf2AssetValue) *NonFungibleTokenAssetTransactionEvent1AllOfAsset {
	this := NonFungibleTokenAssetTransactionEvent1AllOfAsset{}
	this.AssetEventType = assetEventType
	this.AssetId = assetId
	this.Sender = sender
	this.Recipient = recipient
	this.Value = value
	return &this
}

// NewNonFungibleTokenAssetTransactionEvent1AllOfAssetWithDefaults instantiates a new NonFungibleTokenAssetTransactionEvent1AllOfAsset object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNonFungibleTokenAssetTransactionEvent1AllOfAssetWithDefaults() *NonFungibleTokenAssetTransactionEvent1AllOfAsset {
	this := NonFungibleTokenAssetTransactionEvent1AllOfAsset{}
	return &this
}

// GetAssetEventType returns the AssetEventType field value
func (o *NonFungibleTokenAssetTransactionEvent1AllOfAsset) GetAssetEventType() StxAssetTransactionEvent1AllOfAssetAssetEventType {
	if o == nil {
		var ret StxAssetTransactionEvent1AllOfAssetAssetEventType
		return ret
	}

	return o.AssetEventType
}

// GetAssetEventTypeOk returns a tuple with the AssetEventType field value
// and a boolean to check if the value has been set.
func (o *NonFungibleTokenAssetTransactionEvent1AllOfAsset) GetAssetEventTypeOk() (*StxAssetTransactionEvent1AllOfAssetAssetEventType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AssetEventType, true
}

// SetAssetEventType sets field value
func (o *NonFungibleTokenAssetTransactionEvent1AllOfAsset) SetAssetEventType(v StxAssetTransactionEvent1AllOfAssetAssetEventType) {
	o.AssetEventType = v
}

// GetAssetId returns the AssetId field value
func (o *NonFungibleTokenAssetTransactionEvent1AllOfAsset) GetAssetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AssetId
}

// GetAssetIdOk returns a tuple with the AssetId field value
// and a boolean to check if the value has been set.
func (o *NonFungibleTokenAssetTransactionEvent1AllOfAsset) GetAssetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AssetId, true
}

// SetAssetId sets field value
func (o *NonFungibleTokenAssetTransactionEvent1AllOfAsset) SetAssetId(v string) {
	o.AssetId = v
}

// GetSender returns the Sender field value
func (o *NonFungibleTokenAssetTransactionEvent1AllOfAsset) GetSender() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Sender
}

// GetSenderOk returns a tuple with the Sender field value
// and a boolean to check if the value has been set.
func (o *NonFungibleTokenAssetTransactionEvent1AllOfAsset) GetSenderOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Sender, true
}

// SetSender sets field value
func (o *NonFungibleTokenAssetTransactionEvent1AllOfAsset) SetSender(v string) {
	o.Sender = v
}

// GetRecipient returns the Recipient field value
func (o *NonFungibleTokenAssetTransactionEvent1AllOfAsset) GetRecipient() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Recipient
}

// GetRecipientOk returns a tuple with the Recipient field value
// and a boolean to check if the value has been set.
func (o *NonFungibleTokenAssetTransactionEvent1AllOfAsset) GetRecipientOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Recipient, true
}

// SetRecipient sets field value
func (o *NonFungibleTokenAssetTransactionEvent1AllOfAsset) SetRecipient(v string) {
	o.Recipient = v
}

// GetValue returns the Value field value
func (o *NonFungibleTokenAssetTransactionEvent1AllOfAsset) GetValue() TokenTransferTransactionPostConditionsInnerAnyOf2AssetValue {
	if o == nil {
		var ret TokenTransferTransactionPostConditionsInnerAnyOf2AssetValue
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *NonFungibleTokenAssetTransactionEvent1AllOfAsset) GetValueOk() (*TokenTransferTransactionPostConditionsInnerAnyOf2AssetValue, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *NonFungibleTokenAssetTransactionEvent1AllOfAsset) SetValue(v TokenTransferTransactionPostConditionsInnerAnyOf2AssetValue) {
	o.Value = v
}

func (o NonFungibleTokenAssetTransactionEvent1AllOfAsset) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NonFungibleTokenAssetTransactionEvent1AllOfAsset) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["asset_event_type"] = o.AssetEventType
	toSerialize["asset_id"] = o.AssetId
	toSerialize["sender"] = o.Sender
	toSerialize["recipient"] = o.Recipient
	toSerialize["value"] = o.Value
	return toSerialize, nil
}

func (o *NonFungibleTokenAssetTransactionEvent1AllOfAsset) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"asset_event_type",
		"asset_id",
		"sender",
		"recipient",
		"value",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varNonFungibleTokenAssetTransactionEvent1AllOfAsset := _NonFungibleTokenAssetTransactionEvent1AllOfAsset{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varNonFungibleTokenAssetTransactionEvent1AllOfAsset)

	if err != nil {
		return err
	}

	*o = NonFungibleTokenAssetTransactionEvent1AllOfAsset(varNonFungibleTokenAssetTransactionEvent1AllOfAsset)

	return err
}

type NullableNonFungibleTokenAssetTransactionEvent1AllOfAsset struct {
	value *NonFungibleTokenAssetTransactionEvent1AllOfAsset
	isSet bool
}

func (v NullableNonFungibleTokenAssetTransactionEvent1AllOfAsset) Get() *NonFungibleTokenAssetTransactionEvent1AllOfAsset {
	return v.value
}

func (v *NullableNonFungibleTokenAssetTransactionEvent1AllOfAsset) Set(val *NonFungibleTokenAssetTransactionEvent1AllOfAsset) {
	v.value = val
	v.isSet = true
}

func (v NullableNonFungibleTokenAssetTransactionEvent1AllOfAsset) IsSet() bool {
	return v.isSet
}

func (v *NullableNonFungibleTokenAssetTransactionEvent1AllOfAsset) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNonFungibleTokenAssetTransactionEvent1AllOfAsset(val *NonFungibleTokenAssetTransactionEvent1AllOfAsset) *NullableNonFungibleTokenAssetTransactionEvent1AllOfAsset {
	return &NullableNonFungibleTokenAssetTransactionEvent1AllOfAsset{value: val, isSet: true}
}

func (v NullableNonFungibleTokenAssetTransactionEvent1AllOfAsset) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNonFungibleTokenAssetTransactionEvent1AllOfAsset) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


