/*
Stacks Blockchain API

Welcome to the API reference overview for the [Stacks Blockchain API](https://docs.hiro.so/stacks-blockchain-api).        [Download Postman collection](https://hirosystems.github.io/stacks-blockchain-api/collection.json)

API version: v8.1.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package stacks_blockchain_api_client

import (
	"encoding/json"
	"fmt"
)


// GetBurnBlockHeightOrHashParameter struct for GetBurnBlockHeightOrHashParameter
type GetBurnBlockHeightOrHashParameter struct {
	Int32 *int32
	String *string
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *GetBurnBlockHeightOrHashParameter) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into Int32
	err = json.Unmarshal(data, &dst.Int32);
	if err == nil {
		jsonInt32, _ := json.Marshal(dst.Int32)
		if string(jsonInt32) == "{}" { // empty struct
			dst.Int32 = nil
		} else {
			return nil // data stored in dst.Int32, return on the first match
		}
	} else {
		dst.Int32 = nil
	}

	// try to unmarshal JSON data into String
	err = json.Unmarshal(data, &dst.String);
	if err == nil {
		jsonString, _ := json.Marshal(dst.String)
		if string(jsonString) == "{}" { // empty struct
			dst.String = nil
		} else {
			return nil // data stored in dst.String, return on the first match
		}
	} else {
		dst.String = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(GetBurnBlockHeightOrHashParameter)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src *GetBurnBlockHeightOrHashParameter) MarshalJSON() ([]byte, error) {
	if src.Int32 != nil {
		return json.Marshal(&src.Int32)
	}

	if src.String != nil {
		return json.Marshal(&src.String)
	}

	return nil, nil // no data in anyOf schemas
}


type NullableGetBurnBlockHeightOrHashParameter struct {
	value *GetBurnBlockHeightOrHashParameter
	isSet bool
}

func (v NullableGetBurnBlockHeightOrHashParameter) Get() *GetBurnBlockHeightOrHashParameter {
	return v.value
}

func (v *NullableGetBurnBlockHeightOrHashParameter) Set(val *GetBurnBlockHeightOrHashParameter) {
	v.value = val
	v.isSet = true
}

func (v NullableGetBurnBlockHeightOrHashParameter) IsSet() bool {
	return v.isSet
}

func (v *NullableGetBurnBlockHeightOrHashParameter) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetBurnBlockHeightOrHashParameter(val *GetBurnBlockHeightOrHashParameter) *NullableGetBurnBlockHeightOrHashParameter {
	return &NullableGetBurnBlockHeightOrHashParameter{value: val, isSet: true}
}

func (v NullableGetBurnBlockHeightOrHashParameter) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetBurnBlockHeightOrHashParameter) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


