/*
Stacks Blockchain API

Welcome to the API reference overview for the [Stacks Blockchain API](https://docs.hiro.so/stacks-blockchain-api).        [Download Postman collection](https://hirosystems.github.io/stacks-blockchain-api/collection.json)

API version: v8.1.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package stacks_blockchain_api_client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TokenTransferTransactionPostConditionsInnerAnyOfPrincipalAnyOf2 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TokenTransferTransactionPostConditionsInnerAnyOfPrincipalAnyOf2{}

// TokenTransferTransactionPostConditionsInnerAnyOfPrincipalAnyOf2 struct for TokenTransferTransactionPostConditionsInnerAnyOfPrincipalAnyOf2
type TokenTransferTransactionPostConditionsInnerAnyOfPrincipalAnyOf2 struct {
	TypeId string `json:"type_id"`
	Address string `json:"address"`
	ContractName string `json:"contract_name"`
}

type _TokenTransferTransactionPostConditionsInnerAnyOfPrincipalAnyOf2 TokenTransferTransactionPostConditionsInnerAnyOfPrincipalAnyOf2

// NewTokenTransferTransactionPostConditionsInnerAnyOfPrincipalAnyOf2 instantiates a new TokenTransferTransactionPostConditionsInnerAnyOfPrincipalAnyOf2 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTokenTransferTransactionPostConditionsInnerAnyOfPrincipalAnyOf2(typeId string, address string, contractName string) *TokenTransferTransactionPostConditionsInnerAnyOfPrincipalAnyOf2 {
	this := TokenTransferTransactionPostConditionsInnerAnyOfPrincipalAnyOf2{}
	this.TypeId = typeId
	this.Address = address
	this.ContractName = contractName
	return &this
}

// NewTokenTransferTransactionPostConditionsInnerAnyOfPrincipalAnyOf2WithDefaults instantiates a new TokenTransferTransactionPostConditionsInnerAnyOfPrincipalAnyOf2 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTokenTransferTransactionPostConditionsInnerAnyOfPrincipalAnyOf2WithDefaults() *TokenTransferTransactionPostConditionsInnerAnyOfPrincipalAnyOf2 {
	this := TokenTransferTransactionPostConditionsInnerAnyOfPrincipalAnyOf2{}
	return &this
}

// GetTypeId returns the TypeId field value
func (o *TokenTransferTransactionPostConditionsInnerAnyOfPrincipalAnyOf2) GetTypeId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TypeId
}

// GetTypeIdOk returns a tuple with the TypeId field value
// and a boolean to check if the value has been set.
func (o *TokenTransferTransactionPostConditionsInnerAnyOfPrincipalAnyOf2) GetTypeIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TypeId, true
}

// SetTypeId sets field value
func (o *TokenTransferTransactionPostConditionsInnerAnyOfPrincipalAnyOf2) SetTypeId(v string) {
	o.TypeId = v
}

// GetAddress returns the Address field value
func (o *TokenTransferTransactionPostConditionsInnerAnyOfPrincipalAnyOf2) GetAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Address
}

// GetAddressOk returns a tuple with the Address field value
// and a boolean to check if the value has been set.
func (o *TokenTransferTransactionPostConditionsInnerAnyOfPrincipalAnyOf2) GetAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Address, true
}

// SetAddress sets field value
func (o *TokenTransferTransactionPostConditionsInnerAnyOfPrincipalAnyOf2) SetAddress(v string) {
	o.Address = v
}

// GetContractName returns the ContractName field value
func (o *TokenTransferTransactionPostConditionsInnerAnyOfPrincipalAnyOf2) GetContractName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ContractName
}

// GetContractNameOk returns a tuple with the ContractName field value
// and a boolean to check if the value has been set.
func (o *TokenTransferTransactionPostConditionsInnerAnyOfPrincipalAnyOf2) GetContractNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ContractName, true
}

// SetContractName sets field value
func (o *TokenTransferTransactionPostConditionsInnerAnyOfPrincipalAnyOf2) SetContractName(v string) {
	o.ContractName = v
}

func (o TokenTransferTransactionPostConditionsInnerAnyOfPrincipalAnyOf2) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TokenTransferTransactionPostConditionsInnerAnyOfPrincipalAnyOf2) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type_id"] = o.TypeId
	toSerialize["address"] = o.Address
	toSerialize["contract_name"] = o.ContractName
	return toSerialize, nil
}

func (o *TokenTransferTransactionPostConditionsInnerAnyOfPrincipalAnyOf2) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type_id",
		"address",
		"contract_name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTokenTransferTransactionPostConditionsInnerAnyOfPrincipalAnyOf2 := _TokenTransferTransactionPostConditionsInnerAnyOfPrincipalAnyOf2{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTokenTransferTransactionPostConditionsInnerAnyOfPrincipalAnyOf2)

	if err != nil {
		return err
	}

	*o = TokenTransferTransactionPostConditionsInnerAnyOfPrincipalAnyOf2(varTokenTransferTransactionPostConditionsInnerAnyOfPrincipalAnyOf2)

	return err
}

type NullableTokenTransferTransactionPostConditionsInnerAnyOfPrincipalAnyOf2 struct {
	value *TokenTransferTransactionPostConditionsInnerAnyOfPrincipalAnyOf2
	isSet bool
}

func (v NullableTokenTransferTransactionPostConditionsInnerAnyOfPrincipalAnyOf2) Get() *TokenTransferTransactionPostConditionsInnerAnyOfPrincipalAnyOf2 {
	return v.value
}

func (v *NullableTokenTransferTransactionPostConditionsInnerAnyOfPrincipalAnyOf2) Set(val *TokenTransferTransactionPostConditionsInnerAnyOfPrincipalAnyOf2) {
	v.value = val
	v.isSet = true
}

func (v NullableTokenTransferTransactionPostConditionsInnerAnyOfPrincipalAnyOf2) IsSet() bool {
	return v.isSet
}

func (v *NullableTokenTransferTransactionPostConditionsInnerAnyOfPrincipalAnyOf2) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTokenTransferTransactionPostConditionsInnerAnyOfPrincipalAnyOf2(val *TokenTransferTransactionPostConditionsInnerAnyOfPrincipalAnyOf2) *NullableTokenTransferTransactionPostConditionsInnerAnyOfPrincipalAnyOf2 {
	return &NullableTokenTransferTransactionPostConditionsInnerAnyOfPrincipalAnyOf2{value: val, isSet: true}
}

func (v NullableTokenTransferTransactionPostConditionsInnerAnyOfPrincipalAnyOf2) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTokenTransferTransactionPostConditionsInnerAnyOfPrincipalAnyOf2) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


