/*
Stacks Blockchain API

Welcome to the API reference overview for the [Stacks Blockchain API](https://docs.hiro.so/stacks-blockchain-api).        [Download Postman collection](https://hirosystems.github.io/stacks-blockchain-api/collection.json)

API version: v8.1.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package stacks_blockchain_api_client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ContractCallTransactionContractCallFunctionArgsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ContractCallTransactionContractCallFunctionArgsInner{}

// ContractCallTransactionContractCallFunctionArgsInner List of arguments used to invoke the function
type ContractCallTransactionContractCallFunctionArgsInner struct {
	Hex string `json:"hex"`
	Repr string `json:"repr"`
	Name string `json:"name"`
	Type string `json:"type"`
}

type _ContractCallTransactionContractCallFunctionArgsInner ContractCallTransactionContractCallFunctionArgsInner

// NewContractCallTransactionContractCallFunctionArgsInner instantiates a new ContractCallTransactionContractCallFunctionArgsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewContractCallTransactionContractCallFunctionArgsInner(hex string, repr string, name string, type_ string) *ContractCallTransactionContractCallFunctionArgsInner {
	this := ContractCallTransactionContractCallFunctionArgsInner{}
	this.Hex = hex
	this.Repr = repr
	this.Name = name
	this.Type = type_
	return &this
}

// NewContractCallTransactionContractCallFunctionArgsInnerWithDefaults instantiates a new ContractCallTransactionContractCallFunctionArgsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewContractCallTransactionContractCallFunctionArgsInnerWithDefaults() *ContractCallTransactionContractCallFunctionArgsInner {
	this := ContractCallTransactionContractCallFunctionArgsInner{}
	return &this
}

// GetHex returns the Hex field value
func (o *ContractCallTransactionContractCallFunctionArgsInner) GetHex() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Hex
}

// GetHexOk returns a tuple with the Hex field value
// and a boolean to check if the value has been set.
func (o *ContractCallTransactionContractCallFunctionArgsInner) GetHexOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Hex, true
}

// SetHex sets field value
func (o *ContractCallTransactionContractCallFunctionArgsInner) SetHex(v string) {
	o.Hex = v
}

// GetRepr returns the Repr field value
func (o *ContractCallTransactionContractCallFunctionArgsInner) GetRepr() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Repr
}

// GetReprOk returns a tuple with the Repr field value
// and a boolean to check if the value has been set.
func (o *ContractCallTransactionContractCallFunctionArgsInner) GetReprOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Repr, true
}

// SetRepr sets field value
func (o *ContractCallTransactionContractCallFunctionArgsInner) SetRepr(v string) {
	o.Repr = v
}

// GetName returns the Name field value
func (o *ContractCallTransactionContractCallFunctionArgsInner) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ContractCallTransactionContractCallFunctionArgsInner) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ContractCallTransactionContractCallFunctionArgsInner) SetName(v string) {
	o.Name = v
}

// GetType returns the Type field value
func (o *ContractCallTransactionContractCallFunctionArgsInner) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *ContractCallTransactionContractCallFunctionArgsInner) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *ContractCallTransactionContractCallFunctionArgsInner) SetType(v string) {
	o.Type = v
}

func (o ContractCallTransactionContractCallFunctionArgsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ContractCallTransactionContractCallFunctionArgsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["hex"] = o.Hex
	toSerialize["repr"] = o.Repr
	toSerialize["name"] = o.Name
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

func (o *ContractCallTransactionContractCallFunctionArgsInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"hex",
		"repr",
		"name",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varContractCallTransactionContractCallFunctionArgsInner := _ContractCallTransactionContractCallFunctionArgsInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varContractCallTransactionContractCallFunctionArgsInner)

	if err != nil {
		return err
	}

	*o = ContractCallTransactionContractCallFunctionArgsInner(varContractCallTransactionContractCallFunctionArgsInner)

	return err
}

type NullableContractCallTransactionContractCallFunctionArgsInner struct {
	value *ContractCallTransactionContractCallFunctionArgsInner
	isSet bool
}

func (v NullableContractCallTransactionContractCallFunctionArgsInner) Get() *ContractCallTransactionContractCallFunctionArgsInner {
	return v.value
}

func (v *NullableContractCallTransactionContractCallFunctionArgsInner) Set(val *ContractCallTransactionContractCallFunctionArgsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableContractCallTransactionContractCallFunctionArgsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableContractCallTransactionContractCallFunctionArgsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableContractCallTransactionContractCallFunctionArgsInner(val *ContractCallTransactionContractCallFunctionArgsInner) *NullableContractCallTransactionContractCallFunctionArgsInner {
	return &NullableContractCallTransactionContractCallFunctionArgsInner{value: val, isSet: true}
}

func (v NullableContractCallTransactionContractCallFunctionArgsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableContractCallTransactionContractCallFunctionArgsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


