/*
Stacks 2.0+ RPC API

This is the documentation for the `stacks-node` RPC interface. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rpc_client

import (
	"encoding/json"
)

// checks if the PostFeeTransactionResponseschemaEstimationsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PostFeeTransactionResponseschemaEstimationsInner{}

// PostFeeTransactionResponseschemaEstimationsInner struct for PostFeeTransactionResponseschemaEstimationsInner
type PostFeeTransactionResponseschemaEstimationsInner struct {
	FeeRate *float32 `json:"fee_rate,omitempty"`
	Fee *float32 `json:"fee,omitempty"`
}

// NewPostFeeTransactionResponseschemaEstimationsInner instantiates a new PostFeeTransactionResponseschemaEstimationsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPostFeeTransactionResponseschemaEstimationsInner() *PostFeeTransactionResponseschemaEstimationsInner {
	this := PostFeeTransactionResponseschemaEstimationsInner{}
	return &this
}

// NewPostFeeTransactionResponseschemaEstimationsInnerWithDefaults instantiates a new PostFeeTransactionResponseschemaEstimationsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPostFeeTransactionResponseschemaEstimationsInnerWithDefaults() *PostFeeTransactionResponseschemaEstimationsInner {
	this := PostFeeTransactionResponseschemaEstimationsInner{}
	return &this
}

// GetFeeRate returns the FeeRate field value if set, zero value otherwise.
func (o *PostFeeTransactionResponseschemaEstimationsInner) GetFeeRate() float32 {
	if o == nil || IsNil(o.FeeRate) {
		var ret float32
		return ret
	}
	return *o.FeeRate
}

// GetFeeRateOk returns a tuple with the FeeRate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostFeeTransactionResponseschemaEstimationsInner) GetFeeRateOk() (*float32, bool) {
	if o == nil || IsNil(o.FeeRate) {
		return nil, false
	}
	return o.FeeRate, true
}

// HasFeeRate returns a boolean if a field has been set.
func (o *PostFeeTransactionResponseschemaEstimationsInner) HasFeeRate() bool {
	if o != nil && !IsNil(o.FeeRate) {
		return true
	}

	return false
}

// SetFeeRate gets a reference to the given float32 and assigns it to the FeeRate field.
func (o *PostFeeTransactionResponseschemaEstimationsInner) SetFeeRate(v float32) {
	o.FeeRate = &v
}

// GetFee returns the Fee field value if set, zero value otherwise.
func (o *PostFeeTransactionResponseschemaEstimationsInner) GetFee() float32 {
	if o == nil || IsNil(o.Fee) {
		var ret float32
		return ret
	}
	return *o.Fee
}

// GetFeeOk returns a tuple with the Fee field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostFeeTransactionResponseschemaEstimationsInner) GetFeeOk() (*float32, bool) {
	if o == nil || IsNil(o.Fee) {
		return nil, false
	}
	return o.Fee, true
}

// HasFee returns a boolean if a field has been set.
func (o *PostFeeTransactionResponseschemaEstimationsInner) HasFee() bool {
	if o != nil && !IsNil(o.Fee) {
		return true
	}

	return false
}

// SetFee gets a reference to the given float32 and assigns it to the Fee field.
func (o *PostFeeTransactionResponseschemaEstimationsInner) SetFee(v float32) {
	o.Fee = &v
}

func (o PostFeeTransactionResponseschemaEstimationsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PostFeeTransactionResponseschemaEstimationsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.FeeRate) {
		toSerialize["fee_rate"] = o.FeeRate
	}
	if !IsNil(o.Fee) {
		toSerialize["fee"] = o.Fee
	}
	return toSerialize, nil
}

type NullablePostFeeTransactionResponseschemaEstimationsInner struct {
	value *PostFeeTransactionResponseschemaEstimationsInner
	isSet bool
}

func (v NullablePostFeeTransactionResponseschemaEstimationsInner) Get() *PostFeeTransactionResponseschemaEstimationsInner {
	return v.value
}

func (v *NullablePostFeeTransactionResponseschemaEstimationsInner) Set(val *PostFeeTransactionResponseschemaEstimationsInner) {
	v.value = val
	v.isSet = true
}

func (v NullablePostFeeTransactionResponseschemaEstimationsInner) IsSet() bool {
	return v.isSet
}

func (v *NullablePostFeeTransactionResponseschemaEstimationsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePostFeeTransactionResponseschemaEstimationsInner(val *PostFeeTransactionResponseschemaEstimationsInner) *NullablePostFeeTransactionResponseschemaEstimationsInner {
	return &NullablePostFeeTransactionResponseschemaEstimationsInner{value: val, isSet: true}
}

func (v NullablePostFeeTransactionResponseschemaEstimationsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePostFeeTransactionResponseschemaEstimationsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


