/*
Stacks 2.0+ RPC API

This is the documentation for the `stacks-node` RPC interface. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rpc_client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PostFeeTransactionResponseschemaEstimatedCost type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PostFeeTransactionResponseschemaEstimatedCost{}

// PostFeeTransactionResponseschemaEstimatedCost struct for PostFeeTransactionResponseschemaEstimatedCost
type PostFeeTransactionResponseschemaEstimatedCost struct {
	ReadCount int32 `json:"read_count"`
	ReadLength int32 `json:"read_length"`
	Runtime int32 `json:"runtime"`
	WriteCount int32 `json:"write_count"`
	WriteLength int32 `json:"write_length"`
}

type _PostFeeTransactionResponseschemaEstimatedCost PostFeeTransactionResponseschemaEstimatedCost

// NewPostFeeTransactionResponseschemaEstimatedCost instantiates a new PostFeeTransactionResponseschemaEstimatedCost object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPostFeeTransactionResponseschemaEstimatedCost(readCount int32, readLength int32, runtime int32, writeCount int32, writeLength int32) *PostFeeTransactionResponseschemaEstimatedCost {
	this := PostFeeTransactionResponseschemaEstimatedCost{}
	this.ReadCount = readCount
	this.ReadLength = readLength
	this.Runtime = runtime
	this.WriteCount = writeCount
	this.WriteLength = writeLength
	return &this
}

// NewPostFeeTransactionResponseschemaEstimatedCostWithDefaults instantiates a new PostFeeTransactionResponseschemaEstimatedCost object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPostFeeTransactionResponseschemaEstimatedCostWithDefaults() *PostFeeTransactionResponseschemaEstimatedCost {
	this := PostFeeTransactionResponseschemaEstimatedCost{}
	return &this
}

// GetReadCount returns the ReadCount field value
func (o *PostFeeTransactionResponseschemaEstimatedCost) GetReadCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ReadCount
}

// GetReadCountOk returns a tuple with the ReadCount field value
// and a boolean to check if the value has been set.
func (o *PostFeeTransactionResponseschemaEstimatedCost) GetReadCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ReadCount, true
}

// SetReadCount sets field value
func (o *PostFeeTransactionResponseschemaEstimatedCost) SetReadCount(v int32) {
	o.ReadCount = v
}

// GetReadLength returns the ReadLength field value
func (o *PostFeeTransactionResponseschemaEstimatedCost) GetReadLength() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ReadLength
}

// GetReadLengthOk returns a tuple with the ReadLength field value
// and a boolean to check if the value has been set.
func (o *PostFeeTransactionResponseschemaEstimatedCost) GetReadLengthOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ReadLength, true
}

// SetReadLength sets field value
func (o *PostFeeTransactionResponseschemaEstimatedCost) SetReadLength(v int32) {
	o.ReadLength = v
}

// GetRuntime returns the Runtime field value
func (o *PostFeeTransactionResponseschemaEstimatedCost) GetRuntime() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Runtime
}

// GetRuntimeOk returns a tuple with the Runtime field value
// and a boolean to check if the value has been set.
func (o *PostFeeTransactionResponseschemaEstimatedCost) GetRuntimeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Runtime, true
}

// SetRuntime sets field value
func (o *PostFeeTransactionResponseschemaEstimatedCost) SetRuntime(v int32) {
	o.Runtime = v
}

// GetWriteCount returns the WriteCount field value
func (o *PostFeeTransactionResponseschemaEstimatedCost) GetWriteCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.WriteCount
}

// GetWriteCountOk returns a tuple with the WriteCount field value
// and a boolean to check if the value has been set.
func (o *PostFeeTransactionResponseschemaEstimatedCost) GetWriteCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WriteCount, true
}

// SetWriteCount sets field value
func (o *PostFeeTransactionResponseschemaEstimatedCost) SetWriteCount(v int32) {
	o.WriteCount = v
}

// GetWriteLength returns the WriteLength field value
func (o *PostFeeTransactionResponseschemaEstimatedCost) GetWriteLength() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.WriteLength
}

// GetWriteLengthOk returns a tuple with the WriteLength field value
// and a boolean to check if the value has been set.
func (o *PostFeeTransactionResponseschemaEstimatedCost) GetWriteLengthOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WriteLength, true
}

// SetWriteLength sets field value
func (o *PostFeeTransactionResponseschemaEstimatedCost) SetWriteLength(v int32) {
	o.WriteLength = v
}

func (o PostFeeTransactionResponseschemaEstimatedCost) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PostFeeTransactionResponseschemaEstimatedCost) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["read_count"] = o.ReadCount
	toSerialize["read_length"] = o.ReadLength
	toSerialize["runtime"] = o.Runtime
	toSerialize["write_count"] = o.WriteCount
	toSerialize["write_length"] = o.WriteLength
	return toSerialize, nil
}

func (o *PostFeeTransactionResponseschemaEstimatedCost) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"read_count",
		"read_length",
		"runtime",
		"write_count",
		"write_length",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPostFeeTransactionResponseschemaEstimatedCost := _PostFeeTransactionResponseschemaEstimatedCost{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPostFeeTransactionResponseschemaEstimatedCost)

	if err != nil {
		return err
	}

	*o = PostFeeTransactionResponseschemaEstimatedCost(varPostFeeTransactionResponseschemaEstimatedCost)

	return err
}

type NullablePostFeeTransactionResponseschemaEstimatedCost struct {
	value *PostFeeTransactionResponseschemaEstimatedCost
	isSet bool
}

func (v NullablePostFeeTransactionResponseschemaEstimatedCost) Get() *PostFeeTransactionResponseschemaEstimatedCost {
	return v.value
}

func (v *NullablePostFeeTransactionResponseschemaEstimatedCost) Set(val *PostFeeTransactionResponseschemaEstimatedCost) {
	v.value = val
	v.isSet = true
}

func (v NullablePostFeeTransactionResponseschemaEstimatedCost) IsSet() bool {
	return v.isSet
}

func (v *NullablePostFeeTransactionResponseschemaEstimatedCost) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePostFeeTransactionResponseschemaEstimatedCost(val *PostFeeTransactionResponseschemaEstimatedCost) *NullablePostFeeTransactionResponseschemaEstimatedCost {
	return &NullablePostFeeTransactionResponseschemaEstimatedCost{value: val, isSet: true}
}

func (v NullablePostFeeTransactionResponseschemaEstimatedCost) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePostFeeTransactionResponseschemaEstimatedCost) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


