/*
Stacks Blockchain API

Testing BurnBlocksAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package stacks_blockchain_api_client

import (
	"context"
	"testing"

	"github.com/icon-project/stacks-go-sdk/pkg/stacks_blockchain_api_client"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func Test_stacks_blockchain_api_client_BurnBlocksAPIService(t *testing.T) {

	configuration := stacks_blockchain_api_client.NewConfiguration()
	apiClient := stacks_blockchain_api_client.NewAPIClient(configuration)

	t.Run("Test BurnBlocksAPIService GetBlocksByBurnBlock", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var heightOrHash stacks_blockchain_api_client.GetBurnBlockHeightOrHashParameter

		resp, httpRes, err := apiClient.BurnBlocksAPI.GetBlocksByBurnBlock(context.Background(), heightOrHash).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BurnBlocksAPIService GetBurnBlock", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var heightOrHash stacks_blockchain_api_client.GetBurnBlockHeightOrHashParameter

		resp, httpRes, err := apiClient.BurnBlocksAPI.GetBurnBlock(context.Background(), heightOrHash).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BurnBlocksAPIService GetBurnBlocks", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.BurnBlocksAPI.GetBurnBlocks(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
